name: langChain-YouTubeGPT
channels:
 - conda-forge
 - defaults
dependencies:
 - python=3.8.11
 - pip
 - pip:
   - streamlit
   - langchain
   - wikipedia-api
   - openai
   - watchdog
  # - langchain